# Generated by Django 5.1.4 on 2024-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_target_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_done_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
